### ISSUE TITLE
Implement amdmantle64.dll loader

### ISSUE THREAD

**Issue by libcg** [libcg/grvk#11]
Required by Frostbite games (BF4 and Dragon Age: Inquisition). For now these files can be extracted from the Adrenalin 19.4.3 drivers, but not redistributed with GRVK. We need to write our own implementation.

**Comment by xatornet** [comment]
Don't forget mantleaxl64.dll

**Comment by libcg** [comment]
I just remembered that `mantleaxl64.dll` is the extension library that's partially documented. `amdmantle64.dll` is the loader.

**Comment by Cherser-s** [comment]
I doubt that `amdmantle64.dll` is really being used on itself, although it does contain `icdInit`, which `mantle64.dll` uses as well as the real driver code, which is provided through this library onto `mantle64.dll`. `icdInit` function itself is being called on `grInitAndEnumerateGpus` Mantle call from the original `mantle64.dll`.

**Comment by libcg** [comment]
Interesting, that might not be an issue then. I will try BF4 myself soon.

**Comment by Cherser-s** [comment]
heh, good luck, if I'm correct, then at least the game menu will show that mantle "backend" is present

I think bf4 probably only uses `mantleaxl64.dll` for "Advanced msaa state". I wonder whether it's possible to properly map all the fields to vulkan, for basic msaa it seems straightforward, but will probably require to hold off graphics pipeline creation (maybe derivatives will help with perf though).

**Comment by Cherser-s** [comment]
As I expected, the game detects mantle if both `mantle64.dll` and `mantleaxl64.dll` do exist. I didn't yet risk to switch to Mantle  backend though :D

**Comment by libcg** [comment]
I can confirm that too. Closing.
