### ISSUE TITLE
Thief

### ISSUE THREAD

**Issue by xatornet** [libcg/grvk#14]
**Games status:** 

- Thief--> Not working

Details:

Here's Thief Log: (no output error message)

=== GRVK 0.3.0 ===
I/grInitAndEnumerateGpus: app "Thief" (00000000), engine "Unreal3" (00000000), api 00015000
W/grGetExtensionSupport: STUB
W/grGetExtensionSupport: STUB
W/grGetExtensionSupport: STUB
I/grCreateDevice: 10DE:2204 "GeForce RTX 3090" (Vulkan 1.2.155, driver 461.81.0)
W/grCreateQueryPool: STUB

**Comment by libcg** [comment]
@xatornet which DLLs did you use, and where did you place them to get the game to recognize Mantle?

**Comment by xatornet** [comment]
> @xatornet which DLLs did you use, and where did you place them to get the game to recognize Mantle?

Just grvk's mantle64.dll and AMD's mantleaxl64.dll inside Binaries2/Win64. Then you'll be able to select it inside setup. Seems the game's implementation only allows mantle on 64bit

**Comment by libcg** [comment]
@xatornet it's not working for me. can you try this stubbed out `mantleaxl64.dll` and report back? [mantleaxl64.zip](https://github.com/libcg/grvk/files/6145592/mantleaxl64.zip)

**Comment by xatornet** [comment]
> @xatornet it's not working for me. can you try this stubbed out `mantleaxl64.dll` and report back? make sure you delete the old logs before starting the game.
> 
> [mantleaxl64.zip](https://github.com/libcg/grvk/files/6145592/mantleaxl64.zip)
Here's the new log. Same behaviour though:

=== GRVK 0.3.0 ===
I/grInitAndEnumerateGpus: app "Thief" (00000000), engine "Unreal3" (00000000), api 00015000
W/grGetExtensionSupport: STUB
W/grGetExtensionSupport: STUB
W/grGetExtensionSupport: STUB
I/grCreateDevice: 10DE:2204 "GeForce RTX 3090" (Vulkan 1.2.155, driver 461.81.0)
W/grCreateQueryPool: STUB

**Comment by libcg** [comment]
looks like the stub library gets loaded fine then. that's good.

**Comment by libcg** [comment]
Turns out the launcher requires `mantle32.dll`/`mantleaxl32.dll` present in Binaries/Win32 in order to detect Mantle. However the game crashes as soon as I launch it without any logs created.

**Comment by libcg** [comment]
Moving to https://github.com/libcg/grvk/issues/42
