### ISSUE TITLE
Sniper Elite III

### ISSUE THREAD

**Issue by xatornet** [libcg/grvk#15]
**Games status:**

- Sniper Elite III --> Not working

**Here's Log (it is created in the main folder) (no error output message):**

=== GRVK 0.3.0 ===
I/grInitAndEnumerateGpus: app "SniperElite3" (00000000), engine "Asura" (00000000), api 00016000
W/grGetExtensionSupport: STUB
W/grGetExtensionSupport: STUB
W/grGetExtensionSupport: STUB
W/grGetExtensionSupport: STUB
W/grGetExtensionSupport: STUB
W/grGetExtensionSupport: STUB
W/grGetExtensionSupport: STUB
I/grCreateDevice: 10DE:2204 "GeForce RTX 3090" (Vulkan 1.2.155, driver 461.92.0)

**Comment by sehraf** [comment]
Stupid question: Does anybody knows how to test SE3? 
I own a steam copy and places the grvk dlls in the `common/Sniper Elite 3` folder next to the `steam_api.dll` but the launcher - which should have an option to enable mantle - seems not to load these files (e.g. no log is generated).
I was also unable to find a parameter to tell the main executable to use mantle.

**Comment by libcg** [comment]
@sehraf find "Settings Editor.exe" and there should be a checkbox to enable Mantle in there. I haven't tried it myself.

**Comment by xatornet** [comment]
> Stupid question: Does anybody knows how to test SE3?
> I own a steam copy and places the grvk dlls in the `common/Sniper Elite 3` folder next to the `steam_api.dll` but the launcher - which should have an option to enable mantle - seems not to load these files (e.g. no log is generated).
> I was also unable to find a parameter to tell the main executable to use mantle.

From what i've seen, Sniper Elite III used to have a dedicated mantle exe. If there is not one now, maybe the developers removed mantle support or something.

**Comment by sehraf** [comment]
This is all i can find:
```
find . -iname '*.exe'
./bin/SniperElite3.exe
./Launcher/Sniper3Launcher.exe
./redist/DllCheck/DllCheck.exe
```

Looking at [this](https://steamdb.info/depot/238105/) @xatornet  might be right

**Comment by EsdrasTarsis** [comment]
> This is all i can find:
> 
> ```
> find . -iname '*.exe'
> ./bin/SniperElite3.exe
> ./Launcher/Sniper3Launcher.exe
> ./redist/DllCheck/DllCheck.exe
> ```
> 
> Looking at [this](https://steamdb.info/depot/238105/) @xatornet might be right

Yeah, Mantle support was removed from Sniper Elite 3 in the [last update](https://steamdb.info/depot/238105/history/?changeid=M:3494911765143256619) (2019)

**Comment by Faalagorn** [comment]
You should be able to download older version from Steam by downloading old depot; unfortunately I don't have the game to test it…

**Comment by sehraf** [comment]
Thanks! I wasn't aware that [this](https://www.reddit.com/r/Steam/comments/611h5e/guide_how_to_download_older_versions_of_a_game_on/) is a legit feature!

I got the executable using:
`download_depot 238090 238105 7018350587412657571`

Then copy it into the bin folder:
`cp ../../../ubuntu12_32/steamapps/content/app_238090/depot_238105/bin/SniperElite3_Mantle.exe bin `

**Comment by xatornet** [comment]
Well, if the support was removed, then as it is the only game that uses Asura Engine, maybe it's better to use DXVK on this ?

**Comment by xatornet** [comment]
> Thanks! I wasn't aware that [this](https://www.reddit.com/r/Steam/comments/611h5e/guide_how_to_download_older_versions_of_a_game_on/) is a legit feature!
> 
> I got the executable using:
> `download_depot 238090 238105 7018350587412657571`
> 
> Then copy it into the bin folder:
> `cp ../../../ubuntu12_32/steamapps/content/app_238090/depot_238105/bin/SniperElite3_Mantle.exe bin `
> 
> EDIT:
> Running it just does nothing/crashs(Linux) or starts the launcher (windows). No grvk log is created.

could you share the exe file? or pm to me? I don't own the game, so I won't be able to download it.

**Comment by sehraf** [comment]
Here you go [SniperElite3_Mantle.exe.zip](https://github.com/libcg/grvk/files/6151811/SniperElite3_Mantle.exe.zip)
Passwort is the name of this project (all lower case). @libcg if you prefer to not have this here, let me know.

**Comment by xatornet** [comment]
> Here you go [SniperElite3_Mantle.exe.zip](https://github.com/libcg/grvk/files/6151811/SniperElite3_Mantle.exe.zip)
> Password is the name of this project (all lower case). @libcg if you prefer to not have this here, let me know.

Thanks, you can take the file down now, I've downloaded it . Just to avoid any problem. Thanks for it

**Comment by xatornet** [comment]
Ok, i've tested it with the Mantle exe, and it creates a log on the main folder, not bin, here it is:

=== GRVK 0.3.0 ===
I/grInitAndEnumerateGpus: app "SniperElite3" (00000000), engine "Asura" (00000000), api 00016000
W/grGetExtensionSupport: STUB
W/grGetExtensionSupport: STUB
W/grGetExtensionSupport: STUB
W/grGetExtensionSupport: STUB
W/grGetExtensionSupport: STUB
W/grGetExtensionSupport: STUB
W/grGetExtensionSupport: STUB
I/grCreateDevice: 10DE:2204 "GeForce RTX 3090" (Vulkan 1.2.155, driver 461.92.0)

**Comment by sehraf** [comment]
How did your manage to run it? Simply starting it? Are you on Windows or Linux?
I don't have a grvk log in any folder.

**Comment by xatornet** [comment]
> How did your manage to run it? Simply starting it? Are you on Windows or Linux?
> I don't have a grvk log in any folder.

I'm on Windows 10. Just copy mantle32.dll inside bin folder. Also, use AMD's mantleaxl32.dll loader inside bin folder too. Then, the grvk.log will be created inside the game's main folder, outside bin folder.

Please,remember to remove the exe file, I have it already. Thanks

**Comment by sehraf** [comment]
Ah! I was missing `mantleaxl32.dll` which was just in the root folder. Will give it a try tomorrow. 

> Please,remember to remove the exe file, I have it already. Thanks

I've deleted the post.

**Comment by libcg** [comment]
The latest revision of GRVK generates a stubbed `mantleaxl32.dll` that can replace the original one.

**Comment by sehraf** [comment]
0.4.0 update: not working
(grvk.log shows nothing but it created at least)

**Comment by libcg** [comment]
Moving to https://github.com/libcg/grvk/issues/43
