### ISSUE TITLE
linux support ?

### ISSUE THREAD

**Issue by xantares** [libcg/grvk#19]
hello,
It seems it doesnt compile on anything other than windows, is there a limitation somewhere, or it's just a lack of uinterest in the linux port ?

**Comment by sehraf** [comment]
I'm using/testing it primary under Linux without problems.

**Comment by xantares** [comment]
I mean a native linux version, not mingw.

**Comment by K0bin** [comment]
There is no Mantle software on Linux.

**Comment by libcg** [comment]
Mantle is a Windows API only. It's possible to port to Linux, but there are no applications using it.
