### ISSUE TITLE
Bugs on Intel HD 530 GPU on Windows using new 27.20.100.8778 beta driver with EXT_dynamic_state support

### ISSUE THREAD

**Issue by oscarbg** [libcg/grvk#2]
Hi,
great project, keep up the good work :-)

just found new Intel Win driver implements EXT_dynamic_state used by GRVK..
just a quick run run_microwaves shows not running ok..
log:
=== GRVK 0.2.0 ===
I/grInitAndEnumerateGpus: app "(null)" (00000000), engine "(null)" (00000000), api 00000001
W/grGetExtensionSupport: STUB
I/grCreateDevice: 8086:1912 "Intel(R) HD Graphics 530" (Vulkan 1.2.151, driver 0.402.586)
W/initCmdBufferResources: HACK only one descriptor bound
E/grWsiWinQueuePresent: vkQueueSubmit failed
E/grQueueSubmit: vkQueueSubmit failed
E/grWsiWinQueuePresent: vkQueueSubmit failed
E/grQueueSubmit: vkQueueSubmit failed
E/grWsiWinQueuePresent: vkQueueSubmit failed
E/grQueueSubmit: vkQueueSubmit failed

also have you GRVK tested on Anvil Mesa Intel driver on Linux..
at least it has also the required extension..

thanks..

**Comment by oscarbg** [comment]
Similar error log on Linux using Anvil, altough on Ubuntu 20.04 desktop crashed and I had to reboot:

=== GRVK 0.2.0 ===
I/grInitAndEnumerateGpus: app "(null)" (00000000), engine "(null)" (00000000), api 00000001
W/grGetExtensionSupport: STUB
I/grCreateDevice: 8086:1912 "Intel(R) HD Graphics 530 (SKL GT2)" (Vulkan 1.2.145, driver 20.2.99)
W/initCmdBufferResources: HACK only one descriptor bound
E/grQueueSubmit: vkQueueSubmit failed
E/grWsiWinQueuePresent: vkQueueSubmit failed
E/grWaitForFences: vkWaitForFences failed
E/grQueueSubmit: vkQueueSubmit failed
E/grWsiWinQueuePresent: vkQueueSubmit failed
E/grWaitForFences: vkWaitForFences failed
E/grQueueSubmit: vkQueueSubmit failed
E/grWsiWinQueuePresent: vkQueueSubmit failed
E/grWaitForFences: vkWaitForFences failed
E/grQueueSubmit: vkQueueSubmit failed
E/grWsiWinQueuePresent: vkAcquireNextImageKHR failed (-1000001004)

**Comment by libcg** [comment]
Yeah, I get a full system hang with my Intel laptop and mesa 20.2.0. Not sure what's happening.

**Comment by libcg** [comment]
https://gitlab.freedesktop.org/mesa/mesa/-/issues/3767
https://gitlab.freedesktop.org/drm/intel/-/issues/2528

**Comment by libcg** [comment]
@oscarbg ANV is fixed with 1846299, can you try it on the Windows driver?

**Comment by oscarbg** [comment]
yup just tried and now all samples work!. even run_e1m1 sample works, altough it takes some time, doesn't trigger a TDR..

**Comment by libcg** [comment]
Thanks for testing.
