### ISSUE TITLE
Request: support for Github Actions CI? (+artifacts)

### ISSUE THREAD

**Issue by oscarbg** [libcg/grvk#20]
that way we don't have to wait for point releases for up to date testing..
will be more interesting once some games start working an new commits (minor patches) bring new game compatibilty..
thanks..

**Comment by libcg** [comment]
Agreed, I'll look into it.

**Comment by oscarbg** [comment]
thanks..

**Comment by libcg** [comment]
Fixed with 711c0eb829c1ed759c67d9d8c0c9f70ac37ddda3
