### ISSUE TITLE
Image presentation crashes the application after window resize

### ISSUE THREAD

**Issue by Cherser-s** [libcg/grvk#22]
If my window gets resized, I get `Assertion failed: vkRes != VK_ERROR_OUT_OF_DATE_KHR` due to `OUT_OF_DATE` swapchain image acquire result not being handled. This logic doesn't allow to properly launch an application on tiling window managers at all (without forcing floating mode at launch).

I think it's better to get rid of `VK_KHR_Swapchain` usage completely because Mantle doesn't use swapchain logic at all and only uses presentation images, while leaving handling window events (like resizing), which leads to swapchain invalidation to the client. I have already fixed this in ddef5b656d8cd83732f6fd94636c2e719bb8cb2d.

**Comment by libcg** [comment]
Was mostly fixed with 5f603d599. Closing.
