### ISSUE TITLE
grvk says vulkan extensions missing, but my vulkan version is 1.2.199

### ISSUE THREAD

**Issue by kleinermob** [libcg/grvk#35]
=== GRVK 0.5.0 ===
I/00000BDC/grInitAndEnumerateGpus: app "Battlefield" (01000000), engine "Frostbite" (00C00000), api 00018000
I/00000BDC/quirkInit: enabled 0x4
W/00000BDC/grInitAndEnumerateGpus: unhandled alloc callbacks
I/00000BDC/grCreateDevice: 1002:67DF "AMD RADV POLARIS10" (Vulkan 1.2.199, driver 21.99.99)
I/00000BDC/grCreateDevice: DMA queue remapped to compute queue 1
E/00000BDC/grCreateDevice: vkCreateDevice failed (-7)
E/00000BDC/grCreateDevice: missing extension. make sure your Vulkan driver supports:
E/00000BDC/grCreateDevice: - VK_EXT_custom_border_color
E/00000BDC/grCreateDevice: - VK_EXT_extended_dynamic_state
E/00000BDC/grCreateDevice: - VK_EXT_shader_demote_to_helper_invocation
E/00000BDC/grCreateDevice: - VK_KHR_dynamic_rendering
E/00000BDC/grCreateDevice: - VK_KHR_swapchain

**Comment by niobium93** [comment]
You need the latest git version of mesa. Stable versions don't have dynamic rendering yet. "Vulkan version" is basically meaningless.

**Comment by libcg** [comment]
It should work if you get the very latest mesa-git. `VK_KHR_dynamic_rendering` only landed yesterday in RADV.

**Comment by kleinermob** [comment]
Yeah, issue was on my end
