### ISSUE TITLE
Trying it via WINE or STEAM/Proton (using newest wine or GE on Steam)

### ISSUE THREAD

**Issue by goffy59** [libcg/grvk#45]
I am using LInux/POPS OS 21.10 (basically ubuntu/debian)

=== GRVK 0.5.0 ===
I/00000A58/grInitAndEnumerateGpus: app "Battlefield" (01000000), engine "Frostbite" (00C00000), api 00018000
I/00000A58/quirkInit: enabled 0x4
W/00000A58/grInitAndEnumerateGpus: unhandled alloc callbacks
W/00000A58/getGrPhysicalGpuType: unsupported type 4
W/00000A58/getGrPhysicalGpuType: unsupported type 4
I/00000A58/grCreateDevice: 1002:731F "AMD RADV NAVI10" (Vulkan 1.2.182, driver 21.2.2)
I/00000A58/grCreateDevice: DMA queue remapped to compute queue 1
E/00000A58/grCreateDevice: vkCreateDevice failed (-7)
E/00000A58/grCreateDevice: missing extension. make sure your Vulkan driver supports:
E/00000A58/grCreateDevice: - VK_EXT_custom_border_color
E/00000A58/grCreateDevice: - VK_EXT_extended_dynamic_state
E/00000A58/grCreateDevice: - VK_EXT_shader_demote_to_helper_invocation
E/00000A58/grCreateDevice: - VK_KHR_dynamic_rendering
E/00000A58/grCreateDevice: - VK_KHR_swapchain

I have tried installing the AMD driver and from what I can see it should work but it doesn't work. What am I doing wrong?

**Comment by libcg** [comment]
You need mesa-git for `VK_KHR_dynamic_rendering`. Mesa 22.0 will work and should be released in a month or two.
